terminal    = "kitty"
fileManager = "thunar"
launcher = "noctalia msg panel-toggle launcher"
calendar = "noctalia msg panel-toggle control-center calendar"
browser = "brave-browser"
code = "code"

textin = "google-chrome --new-window --start-fullscreen web.whatsapp.com"
moosic = "flatpak run sh.cider.Cider"
tube = "google-chrome --new-window --start-fullscreen www.youtube.com"